steps:
  - name: 'python'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        echo "=== Starting python hello.py===="
        python hello.py
        echo "==== Finish hello.py ====="

options:
  logging: CLOUD_LOGGING_ONLY
